apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-mvc-service
  name: rest-mvc-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rest-mvc-service
  type: ClusterIP
status:
  loadBalancer: {}
